# Generated by Django 5.1.2 on 2024-12-05 11:41

import apps.cellviewer.models.SavedFile
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField()),
                ('row_count', models.IntegerField()),
                ('col_count', models.IntegerField()),
                ('rows', models.TextField()),
                ('cols', models.TextField()),
                ('cells', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.cellviewer.models.SavedFile.saved_file_path_func)),
                ('storage_space_in_b', models.IntegerField()),
                ('row_count', models.IntegerField()),
                ('matrix_row_count', models.IntegerField()),
                ('matrix_col_count', models.IntegerField()),
                ('dimension', models.CharField(max_length=100)),
                ('hash', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dimension', models.CharField(max_length=100)),
                ('files', models.ManyToManyField(related_name='job_files', to='cellviewer.savedfile')),
                ('label_matrix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cellviewer.labelmatrix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
