# Generated by Django 5.1.2 on 2024-12-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelmatrix',
            name='keep_when_unused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='label_matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_label', to='cellviewer.labelmatrix'),
        ),
    ]
