# Generated by Django 5.1.2 on 2024-11-10 23:51

import apps.cellviewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellviewer', '0002_alter_savedjob_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjob',
            name='file_path',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='file',
            field=models.FileField(default='normal_distributed.csv', upload_to=apps.cellviewer.models.file_path),
            preserve_default=False,
        ),
    ]
