# Generated by Django 5.1.2 on 2024-12-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellviewer', '0002_labelmatrix_keep_when_unused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='label_matrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_label', to='cellviewer.labelmatrix'),
        ),
    ]
