# Generated by Django 5.1.2 on 2024-12-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellviewer', '0004_labelmatrix_label_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelmatrix',
            old_name='label_name',
            new_name='matrix_name',
        ),
    ]
