# Generated by Django 5.1.2 on 2024-11-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellviewer', '0005_remove_savedjob_file_remove_savedjob_row_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='files',
            field=models.ManyToManyField(related_name='job_files', to='cellviewer.savedfile'),
        ),
    ]
