# Generated by Django 5.1.2 on 2024-12-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellviewer', '0006_alter_savedjob_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfile',
            name='storage_space_in_mb',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
