# Generated by Django 5.1.2 on 2024-12-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellviewer', '0007_savedfile_storage_space_in_mb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedfile',
            name='storage_space_in_mb',
        ),
        migrations.AddField(
            model_name='savedfile',
            name='storage_space_in_b',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
