# Generated by Django 5.1.2 on 2024-11-25 13:15

import cellviewer.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellviewer', '0004_labelmatrix_savedjob_label_matrix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjob',
            name='file',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='row_count',
        ),
        migrations.CreateModel(
            name='SavedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cellviewer.models.file_path)),
                ('row_count', models.IntegerField()),
                ('matrix_row_count', models.IntegerField()),
                ('matrix_col_count', models.IntegerField()),
                ('dimension', models.CharField(max_length=100)),
                ('hash', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='savedjob',
            name='files',
            field=models.ManyToManyField(related_name='files', to='cellviewer.savedfile'),
        ),
    ]
